### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by KevinChau9527** [OpenIPC/builder#22]
Hello.
I tried to compile according to the README document and encountered an error. The error is printed as follows:

[openipc-builderror.txt](https://github.com/OpenIPC/builder/files/15147007/openipc-builderror.txt)

Cannot execute cross-compiler '/home/kevin/openipc/builder/openipc/output/per-package/toolchain-external-custom/host/opt/ext-toolchain/bin/arm-openipc-linux-gnueabihf-gcc.br_real'

It seems that Buildroot made an error when using the cross-compilation tool chain to compile.
Please tell me how to solve this problem.

Thank you

**Comment by cronyx** [comment]
what is the architecture on your host system?

**Comment by KevinChau9527** [comment]
@cronyx
Host : Ubuntu20.04  amd64

**Comment by KevinChau9527** [comment]
Useful  to build in Ubuntu 22.04, Close issue.
