### ISSUE TITLE
Tapo C110 SSC333 variant with AltoBeam 6012B WIFI chip

### ISSUE THREAD

**Issue by BRFud** [OpenIPC/builder#33]
I bought two Tapo C110 cameras this week to try out OpenIPC. Both use the SSC333 with boards labelled "Tapo C110(EU)/2.20" but they differ in Wifi chip. The first uses the SSW101B, which I believe is baked into the [current builder config for the C110](https://github.com/OpenIPC/builder/blob/master/devices/ssc333_lite_tp-link-tapo-c110-v2/br-ext-chip-sigmastar/configs/ssc333_lite_tp-link-tapo-c110-v2_defconfig) but the second camera has the AltoBeam 6012B WIFI chip (used in other boards supported by OpenIPC). Could someone familiar with the project please add support for this Tapo C110 variant so that the appropriate firmware will be built and added to releases? Thanks!
![IMG_6690](https://github.com/user-attachments/assets/73996bc4-3bff-4f34-bb80-3dd2a241bde8)

**Comment by geedubess** [comment]
I discovered that my wifi chipset is actually a 6012B-X (https://www.altobeam.com/en/contents/72/135.html). That's not yet supported by the atbm60xx driver in openipc!

So, I added it as a package, patched the compilation errors, and my ssc333 + 6012b-x is now working great. I'll work on cleaning it up and issuing a PR, but my biggest question is where I should be pulling the 6012BX driver from.

I found it at https://github.com/gtxaspec/atbm-wifi, but I have no idea if that is a reliable source for the tree. If anyone has any thoughts please do share.

@BRFud, do you have any idea whether you have a 6012B or 6012B-X? What is your USB VID:PID for the device?

**Comment by BRFud** [comment]
@geedubess, thank you for progressing this. I've not been successful in building any patched firmware as yet (getting compile errors running `./builder.sh` even before patching the config - probably due to my inexperience) so I'm grateful you've made some headway.

Looking at my ttl logs I see idVendor=007a, idProduct=888b (same as yours), so does that mean I have a 6012B-X? How did you determine that your chip is actually 6012B-X and not 6012B?

As you can see from my photo the chip says 6012B on the case, not 6012B-X, but I may have incorrectly assumed the wrong model as I have only gone by the chip markings. Is yours the same in appearance?

**Comment by geedubess** [comment]
I tried to use the atbm60xx driver integrated with openipc, but noted during compilation that the driver default VID:PID was 7a:8888 and the driver wasn't doing anything when I loaded it or toggled the chip enable line (which causes 7a:888b to disappear and reappear on the usb bus). I modified the build system to allow me to pass a custom PID of 888b, but then when the driver probed the hardware (log above) it clearly did not work.

After that, I was lucky enough to find a reference to atbm 888b on git in the form of the atbm-wifi repo (above). That then led me to the atbm website which describes the 6012b-x - it sounds like more of a re-design than a re-issue (including BT+80211 vs 80211 only). The atbm-wifi repo (above) is literally the only place I have been able to find source code for the driver and the firmware to load to the chip. Comparing it against the atbm60xx firmware shows many differences. Grab a copy while you can. :)

It's annoying to me that the chip says 6012B as well. I doubt it's malicious, but probably an oversight, possibly a marketing cover-up if they had no choice but to discontinue the original 6012B. If I had to guess, it's probably pin-compatible but I didn't look that deeply. Hey, on the plus side, our hardware might support bluetooth! (if we loaded the right firmware and had the right driver...)

My SSC333+6012B-X has been working great on wifi for the few hours I've been playing with it, and I've now reworked 4 PCBs, flashed my build, and seen the wifi work, so I'm happy.

![image](https://github.com/user-attachments/assets/c8a6004a-5520-48e7-abec-67a09094c257)

**Comment by BRFud** [comment]
Very glad to say my Tapo C110 cameras with the WiFi chip marked AltoBeam 6012B all appear to have Wifi working well now. Thank you @geedubess!

**Comment by NicksonYap** [comment]
thanks @geedubess your `v26` variant for Tapo C110 worked for me!

can be obtained here:
https://github.com/OpenIPC/builder/releases/download/latest/ssc333_lite_tp-link-tapo-c110-v26-nor.tgz

Though, my Tapo C110 is using SC3336 sensor and it's unsupported

looking to see how to fix that

**Comment by sewtop** [comment]
Hi all,

I have a bricked TP-Link Tapo C110(EU)/2.20 (SigmaStar SSC333, SC3336 sensor, AltoBeam 6012B WiFi, XM25QH64C 8MB SPI NOR). Same variant as reported here.

Full chip dump via CH341A shows the first 64KB (0x000000-0x00FFFF) completely erased (all 0xFF) — this is where IPL / IPL_CUST / MXP should live. Boot gets NFHDR ERR on UART, never reaches U-Boot. I have the rest of the SPI layout mapped out (bootcmd, kernel offset 0x80000, etc.) from analyzing the official 1.3.7 update package, but that OTA package doesn't contain the raw IPL/IPL_CUST region.

Does anyone have a working Tapo C110 v2 (same variant: SSC333 + AltoBeam 6012B + XM25QH64C) and could pull a full 8MB SPI NOR dump via CH341A, or at least the first 64KB via `sf read` in U-Boot? Would really appreciate it — happy to share back my full analysis/notes once the unit is recovered.

Thanks!
